version: '3'

services:
  behave:
    build: 
      dockerfile: Dockerfile
      context: .
    environment: 
      BEHAVE_PORT: 8080
      BEHAVE_TLS_ENABLED: 'true'
    volumes: 
      - ./ssl:/app/ssl
    ports: 
      - 8080:8080