version: '3'

services:
    deputy:
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            DEPUTY_PORT: 8080
        volumes:
            - ./ssl:/app/ssl
        ports:
            - 8080:8080
